/**
 * @file    crank_sensor.cpp
 * @brief   60-2 crankshaft trigger wheel driver – RP2350 PIO + IRQ
 */

#include "crank_sensor.h"
#include "../ecu_config.h"

#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "hardware/irq.h"
#include "hardware/timer.h"
#include "pico/stdlib.h"
#include "crank_trigger.pio.h"   // generated by pioasm from .pio file

#include <math.h>
#include <string.h>

// ── PIO instance allocation ──────────────────────────────────
static PIO  s_pio      = pio0;
static uint s_sm_crank = 0;

// ── Tooth / timing state ─────────────────────────────────────
// All variables accessed in the ISR must be volatile.

static volatile uint32_t s_tooth_count    = 0;  // teeth since last sync
static volatile uint32_t s_tooth_in_rev   = 0;  // 0…57 (58 real teeth)
static volatile uint64_t s_last_edge_us   = 0;  // µs timestamp of last edge
static volatile uint64_t s_last_period_us = 0;  // previous inter-tooth period
static volatile uint64_t s_curr_period_us = 0;  // current inter-tooth period

static volatile float    s_rpm           = 0.0f;
static volatile uint16_t s_angle_tdeg    = 0;   // crank angle [0.1°]
static volatile bool     s_synced        = false;

// Angle increment per tooth for a 60-2 wheel (58 real teeth over 360°)
// 360° / 58 ≈ 6.2069°  →  62.069 tenths-of-a-degree
static constexpr float   TOOTH_ANGLE_TDEG = (3600.0f / 58.0f);  // tenths

// Gap detection: if current period > GAP_RATIO × previous → gap
static constexpr float   GAP_RATIO        = 1.8f;

// RPM low-pass filter coefficient (exponential moving average)
static constexpr float   RPM_EMA_ALPHA    = 0.15f;

// ── ISR ──────────────────────────────────────────────────────
/**
 * Called by PIO0 IRQ0 on every rising edge from the crank sensor.
 * Executes on Core 0; must complete well under one tooth period.
 * At 8000 RPM, tooth period ≈ 129 µs  → budget is generous.
 */
static void __isr __not_in_flash_func(crank_isr)(void) {
    // Acknowledge the PIO IRQ flag
    pio_interrupt_clear(s_pio, 0);

    // Drain the FIFO (PIO pushed a "1" each edge)
    while (!pio_sm_is_rx_fifo_empty(s_pio, s_sm_crank)) {
        (void)pio_sm_get(s_pio, s_sm_crank);   // discard payload – we use timestamps
    }

    // Timestamp this edge (µs, 64-bit – never overflows in practice)
    const uint64_t now_us   = time_us_64();
    const uint64_t period   = now_us - s_last_edge_us;
    s_last_edge_us           = now_us;

    // ── Gap detection ──────────────────────────────────────────
    bool is_gap = false;
    if (s_last_period_us > 0 && period > (uint64_t)(s_last_period_us * GAP_RATIO)) {
        is_gap = true;
    }

    if (is_gap) {
        // We just passed the missing-tooth gap → this is TDC reference
        // After the gap the next tooth is tooth #1 (0-based index 0)
        s_tooth_in_rev = 0;
        s_angle_tdeg   = 0;    // reset to 0° crank angle = TDC cyl 1

        if (s_tooth_count >= (TRIGGER_TEETH_TOTAL - TRIGGER_TEETH_MISSING - 2)) {
            s_synced = true;   // we've seen at least one full revolution
        }
        s_tooth_count = 0;
    } else {
        // Normal tooth – advance angle
        s_tooth_in_rev++;
        s_tooth_count++;

        // Accumulate angle (wrap at 7200 = 720° for 4-stroke)
        s_angle_tdeg = (uint16_t)((s_tooth_in_rev * TOOTH_ANGLE_TDEG));
        if (s_angle_tdeg >= 7200) s_angle_tdeg -= 7200;
    }

    // ── RPM calculation ────────────────────────────────────────
    // RPM = (60 s/min) / (period_per_tooth × teeth_per_rev)
    // period in µs → convert: RPM = 60e6 / (period_us × 58)
    if (period > 0 && period < 1000000ULL) {  // sanity: > 0, < 1 s
        float rpm_inst = 60.0e6f / ((float)period * 58.0f);
        // Exponential moving average
        s_rpm = RPM_EMA_ALPHA * rpm_inst + (1.0f - RPM_EMA_ALPHA) * s_rpm;
    }

    s_last_period_us = s_curr_period_us;
    s_curr_period_us = period;
}

// ── Public API ───────────────────────────────────────────────

void crank_sensor_init(void) {
    // Load PIO program
    uint offset = pio_add_program(s_pio, &crank_trigger_program);
    pio_sm_config cfg = crank_trigger_program_get_default_config(offset);

    // Configure the IN pin to CKP GPIO
    sm_config_set_in_pins(&cfg, PIN_CKP);
    pio_gpio_init(s_pio, PIN_CKP);
    pio_sm_set_consecutive_pindirs(s_pio, s_sm_crank, PIN_CKP, 1, false);

    // Full speed (150 MHz) for maximum timing resolution
    sm_config_set_clkdiv(&cfg, 1.0f);

    // Enable IRQ0 from state machine 0
    pio_set_irq0_source_enabled(s_pio, pis_interrupt0, true);
    irq_set_exclusive_handler(PIO0_IRQ_0, crank_isr);
    irq_set_enabled(PIO0_IRQ_0, true);

    pio_sm_init(s_pio, s_sm_crank, offset, &cfg);
    pio_sm_set_enabled(s_pio, s_sm_crank, true);
}

float    crank_get_rpm(void)         { return s_rpm; }
uint16_t crank_get_angle_tdeg(void)  { return s_angle_tdeg; }
bool     crank_is_synced(void)       { return s_synced; }
void     crank_reset_sync(void)      { s_synced = false; s_tooth_count = 0; s_rpm = 0.0f; }
